# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import licensing_pb2 as licensing__pb2


class LicensingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEnclave = channel.unary_unary(
                '/LicensingService/GetEnclave',
                request_serializer=licensing__pb2.GetEnclaveRequest.SerializeToString,
                response_deserializer=licensing__pb2.GetEnclaveReply.FromString,
                )


class LicensingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEnclave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LicensingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEnclave': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnclave,
                    request_deserializer=licensing__pb2.GetEnclaveRequest.FromString,
                    response_serializer=licensing__pb2.GetEnclaveReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LicensingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LicensingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEnclave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LicensingService/GetEnclave',
            licensing__pb2.GetEnclaveRequest.SerializeToString,
            licensing__pb2.GetEnclaveReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
